{
  "@attributes": {
    "stat": "ok",
    "version": 1
  },
  "actions": {
    "action": [
      {
        "type": "Visit",
        "id": 106,
        "accountId": 1,
        "uuid": "41c61a04-7c99-11e5-8000-00000000082e",
        "createdAt": "2016-09-06 10:49:42",
        "campaign": {
          "id": 3,
          "name": "Google Buyer's Guide Campaign",
          "cost": 56000
        },
        "prospect": {
          "firstName": "Angela",
          "lastName": "Lansbury",
          "email": "angela.lansbury@cbs.com",
          "company": "CBS",
          "jobTitle": "Director",
          "country": null,
          "state": null,
          "phone": "877.3.B2B.ROI",
          "isDoNotEmail": false,
          "isDoNotCall": false,
          "isOptedOut": false,
          "isReviewed": true,
          "isStarred": false
        },
        "visitor": {
          "id": 3
        },
        "visit": {
          "id": 1,
          "durationInSeconds" : 184,
          "pageViewCount": 3
        },
        "createdAtUnix": 1445943338,
        "howLongAgo": "2 hrs 12 mins"
      },
      {
        "type": "Webinar",
        "typeConstant": 25,
        "id": 105,
        "accountId": 211972,
        "uuid": "cee25f24-7068-11e6-8000-0000004e4724",
        "createdAt": "2016-09-06 10:48:42",
        "prospect": {
          "salutation": null,
          "firstName": "Test",
          "lastName": "Master",
          "email": "princejohn84@gmail.com",
          "company": "Testorg",
          "website": null,
          "jobTitle": null,
          "department": null,
          "country": null,
          "countryAbbreviation": null,
          "addressOne": null,
          "addressTwo": null,
          "city": null,
          "state": null,
          "stateAbbreviation": null,
          "territory": null,
          "zip": null,
          "phone": null,
          "fax": null,
          "source": null,
          "annualRevenue": null,
          "employees": null,
          "industry": null,
          "yearsInBusiness": null,
          "comments": null,
          "isDoNotEmail": false,
          "isDoNotCall": false,
          "isOptedOut": false,
          "isReviewed": true,
          "isStarred": false,
          "crmLeadFid": "00QB0000002g3NeMAI",
          "crmOwnerFid": "005B00000028yhnIAA",
          "crmUrl": "https://ureddy-xnni.my.salesforce.com/00QB0000002g3NeMAI"
        },
        "webinar": {
          "name": "September Expense Reporting Registration",
          "id": 174,
          "registrationStatus": "Accepted",
          "attendanceStatus": null,
          "connectorName": "GoToWebinar"
        },
        "createdAtUnix": 1472750613,
        "howLongAgo": "2 hrs 16 mins"
      },
      {
        "type": "Landing Page Success",
        "typeConstant": 4,
        "id": 104,
        "accountId": 211972,
        "uuid": "b0239ea4-704f-11e6-8000-0000004d7dc0",
        "createdAt": "2016-09-06 10:48:12",
        "campaign": {
          "id": 2,
          "name": "Website Tracking"
        },
        "prospect": {
          "salutation": null,
          "firstName": "Test",
          "lastName": "Master",
          "email": "princejohn84@gmail.com",
          "company": "Testorg",
          "website": null,
          "jobTitle": null,
          "department": null,
          "country": null,
          "countryAbbreviation": null,
          "addressOne": null,
          "addressTwo": null,
          "city": null,
          "state": null,
          "stateAbbreviation": null,
          "territory": null,
          "zip": null,
          "phone": null,
          "fax": null,
          "source": null,
          "annualRevenue": null,
          "employees": null,
          "industry": null,
          "yearsInBusiness": null,
          "comments": null,
          "isDoNotEmail": false,
          "isDoNotCall": false,
          "isOptedOut": false,
          "isReviewed": true,
          "isStarred": false,
          "crmLeadFid": "00QB0000002g3NeMAI",
          "crmOwnerFid": "005B00000028yhnIAA",
          "crmUrl": "https://ureddy-xnni.my.salesforce.com/00QB0000002g3NeMAI"
        },
        "landingPage": {
          "name": "September Expense Reporting Registration",
          "id": 170
        },
        "visitor": {
          "id": 2004440
        },
        "createdAtUnix": 1472739824,
        "howLongAgo": "2 hrs 34 mins"
      },
      {
        "type": "Landing Page",
        "typeConstant": 4,
        "id": 103,
        "accountId": 211972,
        "uuid": "9d27d1a4-7116-11e6-8000-00000051a588",
        "createdAt": "2016-09-06 10:43:12",
        "campaign": {
          "id": 2,
          "name": "Website Tracking"
        },
        "prospect": {
          "salutation": null,
          "firstName": "Test",
          "lastName": "Master",
          "email": "princejohn84@gmail.com",
          "company": "Testorg",
          "website": null,
          "jobTitle": null,
          "department": null,
          "country": null,
          "countryAbbreviation": null,
          "addressOne": null,
          "addressTwo": null,
          "city": null,
          "state": null,
          "stateAbbreviation": null,
          "territory": null,
          "zip": null,
          "phone": null,
          "fax": null,
          "source": null,
          "annualRevenue": null,
          "employees": null,
          "industry": null,
          "yearsInBusiness": null,
          "comments": null,
          "isDoNotEmail": false,
          "isDoNotCall": false,
          "isOptedOut": false,
          "isReviewed": true,
          "isStarred": false,
          "crmLeadFid": "00QB0000002g3NeMAI",
          "crmOwnerFid": "005B00000028yhnIAA",
          "crmUrl": "https://ureddy-xnni.my.salesforce.com/00QB0000002g3NeMAI"
        },
        "landingPage": {
          "name": "September Expense Reporting Registration",
          "id": 180
        },
        "visitor": {
          "id": 2110598
        },
        "createdAtUnix": 1472825262,
        "howLongAgo": "2 hrs 34 mins"
      },
      {
        "type": "Email Click",
        "typeConstant": 1,
        "id": 102,
        "accountId": 211972,
        "uuid": "9ace7324-7128-11e6-8000-000000523650",
        "createdAt": "2016-09-06 10:43:10",
        "campaign": {
          "id": 942,
          "name": "Olark",
          "cost": 0
        },
        "prospect": {
          "salutation": null,
          "firstName": "Test",
          "lastName": "Master",
          "email": "princejohn84@gmail.com",
          "company": "Testorg",
          "website": null,
          "jobTitle": null,
          "department": null,
          "country": null,
          "countryAbbreviation": null,
          "addressOne": null,
          "addressTwo": null,
          "city": null,
          "state": null,
          "stateAbbreviation": null,
          "territory": null,
          "zip": null,
          "phone": null,
          "fax": null,
          "source": null,
          "annualRevenue": null,
          "employees": null,
          "industry": null,
          "yearsInBusiness": null,
          "comments": null,
          "isDoNotEmail": false,
          "isDoNotCall": false,
          "isOptedOut": false,
          "isReviewed": true,
          "isStarred": false,
          "crmLeadFid": "00QB0000002g3NeMAI",
          "crmOwnerFid": "005B00000028yhnIAA",
          "crmUrl": "https://ureddy-xnni.my.salesforce.com/00QB0000002g3NeMAI"
        },
        "email": {
          "id": 163248,
          "name": "Lenoxsoft Expense Reporting Webinar Invite",
          "isOneToOne": true,
          "subject": "Lenoxsoft Expense Reporting Webinar Invite",
          "isTest": false,
          "bounceSeverityId": 1,
          "bounceSeverityName": "Not A Bounce",
          "pluginName": "",
          "listName" : "September Hot Leads"
        },
        "trackerRedirect": {
          "id": 986,
          "name": "Automatic 1472832955",
          "location": "http://www.pardot.com/septemberwebinar"
        },
        "createdAtUnix": 1472832989,
        "howLongAgo": "2 hrs 35 mins"
      },
      {
        "type": "Email Sent",
        "id": 101,
        "accountId": 1,
        "uuid": "1d03a304-a758-11dc-8000-0000000005bc",
        "createdAt": "2016-09-05 14:43:00",
        "campaign": {
          "id": 2,
          "name": "Email Plug-in"
        },
        "prospect": {
          "firstName": "Angela",
          "lastName": "Lansbury",
          "email": "angela.lansbury@cbs.com",
          "company": "CBS",
          "jobTitle": "Director",
          "country": null,
          "state": null,
          "phone": "877.3.B2B.ROI",
          "isDoNotEmail": false,
          "isDoNotCall": false,
          "isOptedOut": false,
          "isReviewed": true,
          "isStarred": false
        },
        "email": {
          "id": 2,
          "name": "Lenoxsoft Expense Reporting Webinar Invite",
          "isOneToOne": false,
          "subject": "Lenoxsoft Expense Reporting Webinar Invite",
          "isTest": false,
          "bounceSeverityId": 1,
          "bounceSeverityName": "Not A Bounce",
          "pluginName": "",
          "listName" : "September Hot Leads"
        },
        "visitor": {
          "id": 3
        },
        "createdAtUnix": 1197315780,
        "howLongAgo": "3 hrs 12 mins"
      }
    ]
  }
}
